//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "crate_types")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Double")]
    pub short_cm: f64,
    #[sea_orm(column_type = "Double")]
    pub long_cm: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::crates::Entity")]
    Crates,
}

impl Related<super::crates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Crates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
