//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::CrateOrientation;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "crates")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub crate_type_id: i64,
    pub orientation: CrateOrientation,
    pub stack_id: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::crate_items::Entity")]
    CrateItems,
    #[sea_orm(
        belongs_to = "super::crate_types::Entity",
        from = "Column::CrateTypeId",
        to = "super::crate_types::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CrateTypes,
    #[sea_orm(
        belongs_to = "super::stacks::Entity",
        from = "Column::StackId",
        to = "super::stacks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Stacks,
}

impl Related<super::crate_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrateItems.def()
    }
}

impl Related<super::crate_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrateTypes.def()
    }
}

impl Related<super::stacks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stacks.def()
    }
}

impl Related<super::items::Entity> for Entity {
    fn to() -> RelationDef {
        super::crate_items::Relation::Items.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::crate_items::Relation::Crates.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
