//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub map_id: i64,
    #[sea_orm(column_type = "custom(\"citext\")")]
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "custom(\"tsvector\")")]
    pub search_vector: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::crate_items::Entity")]
    CrateItems,
    #[sea_orm(has_many = "super::item_aliases::Entity")]
    ItemAliases,
    #[sea_orm(
        belongs_to = "super::maps::Entity",
        from = "Column::MapId",
        to = "super::maps::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Maps,
}

impl Related<super::crate_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrateItems.def()
    }
}

impl Related<super::item_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemAliases.def()
    }
}

impl Related<super::maps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Maps.def()
    }
}

impl Related<super::crates::Entity> for Entity {
    fn to() -> RelationDef {
        super::crate_items::Relation::Crates.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::crate_items::Relation::Items.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
