//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::PrincipalType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "map_authorizations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub map_id: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub principal_dn: String,
    pub principal_type: PrincipalType,
    pub granted_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::maps::Entity",
        from = "Column::MapId",
        to = "super::maps::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Maps,
}

impl Related<super::maps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Maps.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
