//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::PrincipalType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "maps")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub owner_dn: String,
    pub owner_type: PrincipalType,
    pub is_public: bool,
    #[sea_orm(column_type = "Double")]
    pub width_cm: f64,
    #[sea_orm(column_type = "Double")]
    pub height_cm: f64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::items::Entity")]
    Items,
    #[sea_orm(has_many = "super::map_authorizations::Entity")]
    MapAuthorizations,
    #[sea_orm(has_many = "super::stacks::Entity")]
    Stacks,
}

impl Related<super::items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Items.def()
    }
}

impl Related<super::map_authorizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MapAuthorizations.def()
    }
}

impl Related<super::stacks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stacks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
