//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub mod prelude;

pub mod crate_items;
pub mod crate_types;
pub mod crates;
pub mod item_aliases;
pub mod items;
pub mod map_authorizations;
pub mod maps;
pub mod sea_orm_active_enums;
pub mod stacks;
