//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "stacks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub map_id: i64,
    pub name: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub pos_x_cm: f64,
    #[sea_orm(column_type = "Double")]
    pub pos_y_cm: f64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::crates::Entity")]
    Crates,
    #[sea_orm(
        belongs_to = "super::maps::Entity",
        from = "Column::MapId",
        to = "super::maps::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Maps,
}

impl Related<super::crates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Crates.def()
    }
}

impl Related<super::maps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Maps.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
